name: Generate index.md files

on:
  workflow_dispatch:
  schedule:
    - cron: "*/15 * * * *"

jobs:
  generate:
    name: Generate index.md files
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: 22
          cache: "npm"
      - run: npm ci
      - run: npm run build
        env:
          NODE_OPTIONS: "--max-old-space-size=4192"
      - run: npx tsx bin/generate-index-md.ts
